Needed to update version, to prevent sporadic exceptions of the form: java.lang.NoClassDefFoundError: org/apache/commons/compress/utils/InputStreamStatistics